# Generated by Django 4.2.7 on 2025-12-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('acceso_denegado', 'Acceso Denegado'), ('exportar', 'Exportar Datos'), ('importar', 'Importar Datos'), ('cambio_estado', 'Cambio de Estado'), ('otro', 'Otro')], max_length=20, verbose_name='Acción')),
                ('modulo', models.CharField(choices=[('citas', 'Citas'), ('clientes', 'Clientes'), ('personal', 'Personal'), ('inventario', 'Inventario'), ('proveedores', 'Proveedores'), ('finanzas', 'Finanzas'), ('documentos', 'Documentos'), ('planes_tratamiento', 'Planes de Tratamiento'), ('odontogramas', 'Odontogramas'), ('radiografias', 'Radiografías'), ('servicios', 'Servicios'), ('configuracion', 'Configuración'), ('auditoria', 'Auditoría'), ('sistema', 'Sistema'), ('otro', 'Otro')], max_length=20, verbose_name='Módulo')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles Adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('tipo_objeto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Objeto')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(unique=True)),
                ('paciente_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('paciente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paciente_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('en_espera', 'En Espera'), ('listo_para_atender', 'Listo para Atender'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No Llegó')], default='disponible', max_length=20)),
                ('tipo_consulta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Consulta (Texto Libre)')),
                ('precio_cobrado', models.DecimalField(blank=True, decimal_places=2, help_text='Precio final cobrado (puede diferir del precio base del servicio)', max_digits=10, null=True, verbose_name='Precio Cobrado')),
                ('notas', models.TextField(blank=True, null=True)),
                ('notas_paciente', models.TextField(blank=True, null=True, verbose_name='Notas del Paciente')),
                ('hora_llegada', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Llegada')),
                ('motivo_no_asistencia', models.TextField(blank=True, help_text='Razón por la cual el paciente no asistió a la cita', null=True, verbose_name='Motivo de No Asistencia')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20, null=True, verbose_name='Método de Pago')),
                ('motivo_ajuste_precio', models.TextField(blank=True, help_text='Justificación si el precio difiere del precio base del servicio', null=True, verbose_name='Motivo del Ajuste de Precio')),
                ('notas_finalizacion', models.TextField(blank=True, help_text='Observaciones adicionales al completar la cita', null=True, verbose_name='Notas de Finalización')),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Horario Activo')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Horario de Dentista',
                'verbose_name_plural': 'Horarios de Dentistas',
                'ordering': ['dentista', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Sala')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Sala Activa')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('preventivo', 'Preventivo'), ('restaurador', 'Restaurador'), ('endodoncico', 'Endodóncico'), ('protesico', 'Protésico'), ('quirurgico', 'Quirúrgico'), ('estetico', 'Estético'), ('ortodontico', 'Ortodóncico'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('activo', models.BooleanField(default=True, verbose_name='Servicio Activo')),
                ('requiere_dentista', models.BooleanField(default=True, help_text='Si este servicio requiere un dentista específico', verbose_name='Requiere Dentista')),
                ('duracion_estimada', models.IntegerField(blank=True, help_text='Duración estimada en minutos', null=True, verbose_name='Duración Estimada')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
