# Generated by Django 4.2.7 on 2025-12-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('personal', '0001_initial'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to='personal.perfil', verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='horariodentista',
            name='dentista',
            field=models.ForeignKey(limit_choices_to={'rol': 'dentista'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='personal.perfil', verbose_name='Dentista'),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='pacientes.cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='completada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_completadas', to='personal.perfil', verbose_name='Completada por'),
        ),
        migrations.AddField(
            model_name='cita',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to='personal.perfil'),
        ),
        migrations.AddField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='personal.perfil'),
        ),
    ]
