# Generated by Django 4.2.7 on 2025-12-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial_clinico', '0001_initial'),
        ('citas', '0002_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fase_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='historial_clinico.fasetratamiento', verbose_name='Fase del Tratamiento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='historial_clinico.plantratamiento', verbose_name='Plan de Tratamiento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='citas.tiposervicio', verbose_name='Tipo de Servicio'),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to='personal.perfil', verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='horariodentista',
            unique_together={('dentista', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['-fecha_hora'], name='citas_audit_fecha_h_8f909c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='citas_audit_usuario_a30a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['modulo', '-fecha_hora'], name='citas_audit_modulo_2c3bab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['accion', '-fecha_hora'], name='citas_audit_accion_f8651a_idx'),
        ),
    ]
