# Generated by Django 4.2.7 on 2025-12-07 21:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDocumento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rut', models.CharField(blank=True, help_text='RUT en formato: 12345678-9 (opcional pero recomendado)', max_length=12, null=True, verbose_name='RUT')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True, verbose_name='Fecha de Nacimiento')),
                ('alergias', models.TextField(blank=True, help_text='Lista de alergias conocidas (medicamentos, materiales dentales, anestesia, etc.). MUY IMPORTANTE para la seguridad del paciente.', null=True, verbose_name='Alergias')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('dentista_asignado_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pacientes_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformacionClinica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_clinica', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_alternativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('horario_atencion', models.TextField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('actualizado_el', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuracion_informacionclinica',
                'ordering': ['-actualizado_el'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paciente_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('paciente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paciente_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('paciente_fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('antecedentes_medicos', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, null=True)),
                ('higiene_oral', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_general', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('plan_tratamiento', models.TextField(blank=True, null=True)),
                ('proxima_cita', models.DateTimeField(blank=True, null=True)),
                ('dentista_id', models.BigIntegerField(blank=True, null=True)),
                ('cliente_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_clinico_odontograma',
                'ordering': ['-fecha_creacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radiografia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paciente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paciente_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_tomada', models.DateField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('dentista_id', models.BigIntegerField(blank=True, null=True)),
                ('cliente_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_clinico_radiografia',
                'ordering': ['-fecha_carga'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_dentista', models.BooleanField(default=True)),
                ('duracion_estimada', models.IntegerField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('actualizado_el', models.DateTimeField(blank=True, null=True)),
                ('creado_por_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citas_tiposervicio',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254)),
                ('estrellas', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Envío'), ('enviada', 'Enviada'), ('error', 'Error al Enviar')], default='pendiente', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones_cliente',
                'ordering': ['-creada_el'],
                'unique_together': {('user',)},
            },
        ),
    ]
