# Generated by Django 4.2.7 on 2025-12-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_principales', to='proveedores.proveedor', verbose_name='Proveedor Principal'),
        ),
    ]
