# Generated by Django 4.2.7 on 2025-12-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=6)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('intentos', models.IntegerField(default=0)),
                ('verificado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono_verificado', models.BooleanField(default=False)),
                ('rut', models.CharField(blank=True, help_text='RUT en formato: 12345678-9 (opcional pero recomendado)', max_length=12, null=True, verbose_name='RUT')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True, verbose_name='Fecha de Nacimiento')),
                ('alergias', models.TextField(blank=True, help_text='Lista de alergias conocidas (medicamentos, materiales dentales, anestesia, etc.). MUY IMPORTANTE para la seguridad del paciente.', null=True, verbose_name='Alergias')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
