# Generated by Django 4.2.7 on 2025-12-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial_clinico', '0001_initial'),
        ('citas', '0003_initial'),
        ('pacientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumoodontograma',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_en_odontogramas', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='insumoodontograma',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_utilizados', to='historial_clinico.odontograma'),
        ),
        migrations.AddField(
            model_name='fasetratamiento',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='historial_clinico.plantratamiento', verbose_name='Plan de Tratamiento'),
        ),
        migrations.AddField(
            model_name='estadodiente',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='historial_clinico.odontograma'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='citas.cita', verbose_name='Cita'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='generado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_generados', to='personal.perfil', verbose_name='Generado por'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='odontograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='historial_clinico.odontograma', verbose_name='Odontograma'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='historial_clinico.plantratamiento', verbose_name='Plan de Tratamiento'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='citas.cita', verbose_name='Cita Asociada'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='pacientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='dentista',
            field=models.ForeignKey(limit_choices_to={'rol': 'dentista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_creados', to='personal.perfil', verbose_name='Profesional Tratante'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='explicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_explicados', to='personal.perfil', verbose_name='Profesional Informante'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='historial_clinico.plantratamiento', verbose_name='Plan de Tratamiento'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='historial_clinico.plantillaconsentimiento', verbose_name='Plantilla Utilizada'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='recepcionista_firmante',
            field=models.ForeignKey(blank=True, help_text='Recepcionista que firmó el consentimiento en nombre del paciente', limit_choices_to={'rol': 'administrativo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_firmados_recepcion', to='personal.perfil', verbose_name='Recepcionista que Firmó'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='subido_por',
            field=models.ForeignKey(blank=True, help_text='Personal que subió el documento firmado físicamente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_subidos', to='personal.perfil', verbose_name='Subido por'),
        ),
        migrations.AddIndex(
            model_name='radiografia',
            index=models.Index(fields=['paciente_email'], name='historial_c_pacient_1399d3_idx'),
        ),
        migrations.AddIndex(
            model_name='radiografia',
            index=models.Index(fields=['-fecha_carga'], name='historial_c_fecha_c_7697eb_idx'),
        ),
        migrations.AddIndex(
            model_name='radiografia',
            index=models.Index(fields=['dentista'], name='historial_c_dentist_f2418f_idx'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['-creado_el'], name='historial_c_creado__2cabb3_idx'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['estado'], name='historial_c_estado_0ddbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['dentista', 'estado'], name='historial_c_dentist_76b4df_idx'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['cliente'], name='historial_c_cliente_dce87b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagotratamiento',
            index=models.Index(fields=['plan_tratamiento', '-fecha_pago'], name='historial_c_plan_tr_616613_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fasetratamiento',
            unique_together={('plan', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='estadodiente',
            unique_together={('odontograma', 'numero_diente')},
        ),
        migrations.AddIndex(
            model_name='documentocliente',
            index=models.Index(fields=['cliente', '-fecha_generacion'], name='historial_c_cliente_6a1bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentocliente',
            index=models.Index(fields=['tipo', '-fecha_generacion'], name='historial_c_tipo_bad307_idx'),
        ),
        migrations.AddIndex(
            model_name='documentocliente',
            index=models.Index(fields=['-fecha_generacion'], name='historial_c_fecha_g_0f61e3_idx'),
        ),
        migrations.AddIndex(
            model_name='consentimientoinformado',
            index=models.Index(fields=['cliente', '-fecha_creacion'], name='historial_c_cliente_a7db3a_idx'),
        ),
        migrations.AddIndex(
            model_name='consentimientoinformado',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='historial_c_estado_8aada0_idx'),
        ),
        migrations.AddIndex(
            model_name='consentimientoinformado',
            index=models.Index(fields=['tipo_procedimiento'], name='historial_c_tipo_pr_cbc624_idx'),
        ),
        migrations.AddIndex(
            model_name='consentimientoinformado',
            index=models.Index(fields=['-fecha_creacion'], name='historial_c_fecha_c_9af09c_idx'),
        ),
    ]
