# Generated by Django 4.2.7 on 2025-12-11 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('historial_clinico', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='pacientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='pacientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='plantratamiento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_tratamiento', to='pacientes.cliente', verbose_name='Cliente'),
        ),
    ]
